apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-deploy
  namespace: dev-namespace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
        - name: cal-container
          image: 501170964283.dkr.ecr.ap-south-1.amazonaws.com/cal-app
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cal-service
  namespace: dev-namespace
spec:
  selector:
    app: cal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
